
---

- name: ansible
  hosts: servers
  gather_facts: yes

  tasks:
    - name: Install packages with apt and shell
      apt:
        name: ntp
        state: latest
        update_cache: yes
      when: ansible_distribution_version == "20.04"
